<a href="https://colab.research.google.com/github/Sindhuarush/Intership-work/blob/master/indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [10]:
a[2]

8

In [11]:
a[2:5]

array([ 8, 27, 64])

In [12]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [13]:
 a[ : :-1] 

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [14]:
for i in a:
...     print(i**(1/3.))
...

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [28]:
 B = np.arange(2)
 B

array([0, 1])

In [29]:
np.exp(B)

array([1.        , 2.71828183])

In [30]:
np.sqrt(B)

array([0., 1.])

In [31]:
 C = np.array([8, 4])
>>> np.add(B, C)

array([8, 5])

In [59]:
a = np.array([[(1,2,3)], [(4,5,6)],[(7,8,9)],[(5,6,7)]])
a

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]],

       [[5, 6, 7]]])

In [46]:
a.ndim

3

In [64]:
a[0:3:2]

array([[[1, 2, 3]],

       [[7, 8, 9]]])

In [65]:
a = np.array([[(1,2,3),(1,1,1),(2,2,2)], [(4,5,6),(2,2,2),(3,3,3)],[(7,8,9),(1,1,1),(2,2,2)],[(5,6,7),(2,2,2),(3,3,3)]])
a

array([[[1, 2, 3],
        [1, 1, 1],
        [2, 2, 2]],

       [[4, 5, 6],
        [2, 2, 2],
        [3, 3, 3]],

       [[7, 8, 9],
        [1, 1, 1],
        [2, 2, 2]],

       [[5, 6, 7],
        [2, 2, 2],
        [3, 3, 3]]])

In [72]:
a[2,1:3]

array([[1, 1, 1],
       [2, 2, 2]])

In [0]:
 simple_array = np.array([2.3, 0.1, -9.1])