<a href="https://colab.research.google.com/github/Sindhuarush/Intership-work/blob/master/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
>>> a = np.array([[1.0, 2.0], [3.0, 4.0]])
>>> print(a)

[[1. 2.]
 [3. 4.]]


In [7]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [8]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

"eye"-represents "I"

In [17]:
j = np.array([[0, 2], [1, 0]])
j @ j 

array([[2, 0],
       [0, 2]])

In [18]:
np.trace(u)

2.0

In [19]:
 y = np.array([[5], [7]])
>>> np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [15]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))