<a href="https://colab.research.google.com/github/Sindhuarush/Intership-work/blob/master/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x=7
print(x)

7


In [2]:

import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
np.__version__

'1.16.4'

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int64'

In [8]:
a.itemsize

8

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
 b = np.array([6, 7, 8])
 b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [20]:
import numpy as np
>>> a = np.arange(30).reshape(2,5,3)
>>> a


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [21]:
a.ndim

3

In [22]:
a.shape

(2, 5, 3)

In [25]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [26]:
a.dtype

dtype('int64')

In [27]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [0]:
a = np.array([1,2,3,4])

In [88]:

b = np.array([[(1.5,2,3), (4,5,6)], [(1,2,3), (2,3,4)]])
b

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[1. , 2. , 3. ],
        [2. , 3. , 4. ]]])

In [89]:
b.ndim

3

In [90]:
a * b

array([[[ 4.5,  6. ,  9. ],
        [12. , 15. , 18. ]],

       [[ 3. ,  6. ,  9. ],
        [ 6. ,  9. , 12. ]]])

In [91]:
a @ b

ValueError: ignored

In [92]:
a.dot(b)

ValueError: ignored

In [31]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [34]:
 b = np.array([(1.5,2,3), (4,5,6), (1,2,3)])
>>> b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [1. , 2. , 3. ]])

In [35]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [36]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [38]:
np.empty( (2,3) )

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [39]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [40]:
np.arange( 0, 2, 0.3 )      

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [41]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [43]:
 from numpy import pi
 np.linspace( 0, 2, 9 )  

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [53]:
 x = np.linspace( 0, 2*pi, 100 )        
 f = np.sin(x)
 f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [47]:
a = np.arange(6)                         # 1d array
print(a)


[0 1 2 3 4 5]


In [48]:
 b = np.arange(12).reshape(4,3)           # 2d array
 print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [49]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [50]:
 print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [51]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [54]:
 a = np.array( [20,30,40,50] )
 b = np.arange( 4 )
 b

array([0, 1, 2, 3])

In [56]:
c = a-b
c

array([20, 29, 38, 47])

In [57]:
b**2

array([0, 1, 4, 9])

In [58]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [59]:
a<35

array([ True,  True, False, False])

In [60]:
 A = np.array( [[1,1],
...             [0,1]] )
 B = np.array( [[2,0],
...             [3,4]] )
 A * B      

array([[2, 0],
       [0, 4]])

In [61]:
 A @ B 

array([[5, 4],
       [3, 4]])

In [62]:
A.dot(B) 

array([[5, 4],
       [3, 4]])

In [83]:
a = np.ones((2,3), dtype=float)
b = np.random.random((2,3))
a *= 3
a

array([[3., 3., 3.],
       [3., 3., 3.]])

In [84]:
 b += a
 b

array([[3.2097916 , 3.0322472 , 3.26156977],
       [3.53649459, 3.57738056, 3.64148474]])

In [65]:
a += b 

TypeError: ignored

In [66]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [67]:
 c = a+b
 c

array([1.        , 2.57079633, 4.14159265])

In [68]:
c.dtype.name

'float64'

In [69]:
 d = np.exp(c*1j)
 d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [70]:
d.dtype.name

'complex128'

In [71]:
a = np.random.random((2,3))
a

array([[0.85937729, 0.59271715, 0.17217824],
       [0.78496121, 0.34145302, 0.85604519]])

In [72]:
a.sum()

3.606732104514279

In [73]:
a.min()

0.1721782433009299

In [74]:
a.max()

0.8593772863772874

In [93]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [95]:
 b.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [77]:
b.min(axis=1)

array([0, 4, 8])

In [78]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])